apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  # 1. Persistent Volume et Persistent Volume Claim
  - persistent-volume.yaml
  - persistent-volume-claim.yaml

  # 2. ConfigMap
  - configmap.yaml

  # 3. Secret
  - secret.yaml

  # 4. StatefulSet
  - statefulset.yaml

  # 5. Service
  - service.yaml

  # 6. Horizontal Pod Autoscaler (HPA)
  - horizontal-pod-autoscaler.yaml

namespace: direct-assurance  # Si vous avez un namespace spécifique
